# Generated by Django 2.1.7 on 2019-04-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='port',
            name='installs_libs',
        ),
        migrations.AlterField(
            model_name='buildhistory',
            name='builder_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.Builder'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='ports',
            field=models.ManyToManyField(db_index=True, related_name='maintainers', to='ports.Port'),
        ),
        migrations.AlterField(
            model_name='port',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
