# Generated by Django 2.1.7 on 2019-05-12 18:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_auto_20190427_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('osx_version', models.CharField(max_length=10)),
                ('macports_version', models.CharField(max_length=10)),
                ('xcode_version', models.CharField(max_length=10)),
                ('os_arch', models.CharField(max_length=10)),
                ('active_ports', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
