# Generated by Django 2.1.7 on 2019-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0004_auto_20190514_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainer',
            name='domain',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='github',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
