# Generated by Django 2.1.7 on 2019-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_auto_20190521_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='replaced_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
