# Generated by Django 2.1.7 on 2019-05-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0006_auto_20190525_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='epoch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='homepage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='license',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='long_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='platforms',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='variants',
            field=models.TextField(null=True),
        ),
    ]
