# Generated by Django 2.1.7 on 2019-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0007_auto_20190525_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='epoch',
            field=models.BigIntegerField(null=True),
        ),
    ]
