# Generated by Django 2.1.7 on 2019-05-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0008_auto_20190525_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainer',
            name='domain',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='github',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='port',
            name='closedmaintainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='port',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='port',
            name='long_description',
            field=models.TextField(default=''),
        ),
    ]
