# Generated by Django 2.1.7 on 2019-05-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0009_auto_20190528_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='port',
            name='variants',
        ),
        migrations.AlterField(
            model_name='port',
            name='epoch',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='homepage',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='port',
            name='license',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='version',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.Port'),
        ),
    ]
