# Generated by Django 2.1.7 on 2019-05-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0010_auto_20190530_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ports.Port'),
        ),
    ]
