# Generated by Django 2.1.7 on 2019-05-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0011_auto_20190530_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('port_name', 'type')},
        ),
    ]
