# Generated by Django 2.1.7 on 2019-05-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0012_auto_20190531_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintainer',
            unique_together={('name', 'domain', 'github')},
        ),
    ]
