# Generated by Django 2.1.7 on 2019-06-01 11:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0013_auto_20190531_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
