# Generated by Django 2.1.7 on 2019-06-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0014_user_full_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_ports',
        ),
    ]
