# Generated by Django 2.1.7 on 2019-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0015_remove_user_active_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
