# Generated by Django 2.1.7 on 2019-06-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0016_auto_20190604_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='time_elapsed',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='buildhistory',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
