# Generated by Django 2.1.7 on 2019-06-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0017_auto_20190605_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='time_elapsed',
            field=models.TimeField(null=True),
        ),
    ]
