# Generated by Django 2.1.7 on 2019-06-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0018_auto_20190605_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='time_start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
