# Generated by Django 2.1.7 on 2019-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0019_auto_20190605_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osx_version', models.CharField(db_index=True, max_length=20)),
                ('month', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('users', models.ManyToManyField(related_name='users', to='ports.User')),
            ],
        ),
    ]
