# Generated by Django 2.1.7 on 2019-06-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0020_osdistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildhistory',
            name='build_url',
        ),
        migrations.RemoveField(
            model_name='buildhistory',
            name='watcher_url',
        ),
    ]
