# Generated by Django 2.1.7 on 2019-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0022_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='port_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buildhistory',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buildhistory',
            name='time_start',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name', 'builder_name', '-build_id'], name='ports_build_port_na_f1d25f_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name', 'status', 'builder_name'], name='ports_build_port_na_94f9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['-time_start'], name='ports_build_time_st_67b2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name'], name='ports_build_port_na_aea401_idx'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['status'], name='ports_build_status_76abdf_idx'),
        ),
    ]
