# Generated by Django 2.1.7 on 2019-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0023_auto_20190619_1318'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['port_name', 'builder_name'], name='ports_build_port_na_3bfa4c_idx'),
        ),
    ]
