# Generated by Django 2.1.7 on 2019-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0024_auto_20190622_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='port_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buildhistory',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
