# Generated by Django 2.1.7 on 2019-06-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0025_auto_20190623_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
