# Generated by Django 2.1.7 on 2019-06-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0027_auto_20190628_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('requested', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.Submission')),
            ],
        ),
    ]
