# Generated by Django 2.1.7 on 2019-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0028_portinstallation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portinstallation',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
