# Generated by Django 2.1.7 on 2019-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0029_auto_20190628_1723'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portinstallation',
            index=models.Index(fields=['submission'], name='ports_porti_submiss_9f52b0_idx'),
        ),
        migrations.AddIndex(
            model_name='portinstallation',
            index=models.Index(fields=['port'], name='ports_porti_port_ff6a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['timestamp'], name='ports_submi_timesta_ef1081_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user'], name='ports_submi_user_id_aa7fba_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-timestamp'], name='ports_submi_user_id_e8af69_idx'),
        ),
    ]
