# Generated by Django 2.1.7 on 2019-06-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0030_auto_20190628_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='dependencies',
            field=models.ManyToManyField(to='ports.Port'),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='domain',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='github',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='ports',
            field=models.ManyToManyField(related_name='maintainers', to='ports.Port'),
        ),
        migrations.AddIndex(
            model_name='buildhistory',
            index=models.Index(fields=['builder_name'], name='ports_build_builder_289e95_idx'),
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['port_name'], name='ports_depen_port_na_647c68_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['github'], name='ports_maint_github_4a7ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainer',
            index=models.Index(fields=['name', 'domain'], name='ports_maint_name_edcd1d_idx'),
        ),
    ]
