# Generated by Django 2.1.7 on 2019-07-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0031_auto_20190629_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
