# Generated by Django 2.1.7 on 2019-07-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0032_auto_20190701_1812'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'timestamp'], name='ports_submi_user_id_ade7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['os_version'], name='ports_submi_os_vers_0b58c5_idx'),
        ),
    ]
